### ISSUE TITLE
Feature Development: Activity Tracker Integration for Wellness App Personal Profile

### ISSUE THREAD

**Issue by ihaseebullah** [ihaseebullah/Wellness#4]
We are developing an activity tracker to function as the personal profile within our wellness app. This profile will eventually integrate with other personal profiles from various mini-apps to create a unified personal profile within a larger super app.

This issue serves as a progress update on integrating several modules into our wellness app's personal profile:

Hydration Module: We're implementing features to track daily water intake and provide hydration recommendations based on user activity and environment.

Smoking Cessation Module: Our module supports users in tracking smoking habits, setting goals for reduction or cessation, and provides motivational support and resources.

Workout Module: This module allows users to log their exercise routines, track progress, and receive personalized workout recommendations based on their fitness goals.

Medication Module: We're developing features to help users manage their medication schedules, set reminders, and track adherence to prescribed regimens.

Each module is designed to enhance the overall user experience by providing comprehensive health and wellness tracking capabilities. This update marks our ongoing efforts to integrate these modules seamlessly into the wellness app's personal profile.

Next Steps:

Complete integration of remaining features for each module.
Conduct testing and gather user feedback to refine module functionalities.
Prepare for the final integration into the super app's unified personal profile.
We welcome any feedback, suggestions, or questions regarding the progress and development of these modules.

**Comment by jahadtariq** [comment]
How  are you planning to store the progress of each module in personal profile of wellness hub ?

**Comment by ihaseebullah** [comment]
> How  are you planning to store the progress of each module in personal profile of wellness hub ?

What i think is that we can calculate the data or store pre calculated data within a database collection say activaties for now, what do you think?

**Comment by jahadtariq** [comment]
The activities can alone act as our personal profile. As you said we can create personal profile of mini-application on the go while we calculate the progress on frontend.
